<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>t4_pr1_JhonOsorio29</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Model-data\" />
    <Folder Include="Test\" />
    <Folder Include="Service\" />
  </ItemGroup>

</Project>
